"""
新增第三方应用接入相关表（OAuth2 客户端凭证模式）

包含：oauth_apps / api_app_tokens / api_app_audit_logs

Revision ID: 20260818_0001
Revises: 20260807_0025
Create Date: 2026-08-18
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect

# 与模型 app/models/oauth_app.py 一致：UUID 列在 PostgreSQL 下编译为原生 UUID，
# 在 SQLite 下为 String(36)。不要使用 sa.String(36) 表示 UUID 主键/外键列，
# 否则在 PostgreSQL 下外键会从 VARCHAR 指向 UUID 主键，触发类型不兼容错误导致迁移失败。
from app.db_types import CompatUUID as UUID, CompatJSON as JSON


# revision identifiers, used by Alembic.
revision = '20260818_0001'
# 数据库当前版本为 20260807_0025（高级权限迁移），恢复该迁移脚本后链完整：
# 20260806_0024 -> 20260807_0025 -> 20260818_0001
down_revision = '20260807_0025'
branch_labels = None
depends_on = None


def _table_exists(name: str) -> bool:
    inspector = inspect(op.get_bind())
    return name in inspector.get_table_names()


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    if not _table_exists('oauth_apps'):
        op.create_table(
            'oauth_apps',
            sa.Column('id', UUID(), nullable=False),
            sa.Column('app_name', sa.String(100), nullable=False),
            sa.Column('client_id', sa.String(64), nullable=False),
            sa.Column('client_secret_hash', sa.String(255), nullable=False),
            sa.Column('owner_id', UUID(), nullable=False),
            sa.Column('callback_url', sa.String(512), nullable=True),
            sa.Column('allowed_bases', JSON(), nullable=False),
            sa.Column('scopes', sa.String(255), nullable=False),
            sa.Column('is_active', sa.Boolean(), nullable=False, default=True),
            sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
            sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
            sa.PrimaryKeyConstraint('id'),
            sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
            sa.UniqueConstraint('client_id')
        )
        op.create_index('ix_oauth_apps_client_id', 'oauth_apps', ['client_id'])
        op.create_index('ix_oauth_apps_owner_id', 'oauth_apps', ['owner_id'])

    if not _table_exists('api_app_tokens'):
        op.create_table(
            'api_app_tokens',
            sa.Column('id', UUID(), nullable=False),
            sa.Column('jti', sa.String(36), nullable=False),
            sa.Column('app_id', UUID(), nullable=False),
            sa.Column('scope', sa.String(255), nullable=False),
            sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
            sa.Column('revoked', sa.Boolean(), nullable=False, default=False),
            sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
            sa.PrimaryKeyConstraint('id'),
            sa.ForeignKeyConstraint(['app_id'], ['oauth_apps.id'], ondelete='CASCADE'),
            sa.UniqueConstraint('jti')
        )
        op.create_index('ix_api_app_tokens_app_id', 'api_app_tokens', ['app_id'])
        op.create_index('ix_api_app_tokens_jti', 'api_app_tokens', ['jti'])

    if not _table_exists('api_app_audit_logs'):
        op.create_table(
            'api_app_audit_logs',
            sa.Column('id', UUID(), nullable=False),
            sa.Column('app_id', UUID(), nullable=True),
            sa.Column('action', sa.String(50), nullable=False),
            sa.Column('detail', sa.Text(), nullable=True),
            sa.Column('ip', sa.String(64), nullable=True),
            sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
            sa.PrimaryKeyConstraint('id'),
            sa.ForeignKeyConstraint(['app_id'], ['oauth_apps.id'], ondelete='SET NULL')
        )
        op.create_index('ix_api_app_audit_logs_app_id', 'api_app_audit_logs', ['app_id'])
        op.create_index('ix_api_app_audit_logs_created_at', 'api_app_audit_logs', ['created_at'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    if _table_exists('api_app_audit_logs'):
        op.drop_index('ix_api_app_audit_logs_created_at', table_name='api_app_audit_logs')
        op.drop_index('ix_api_app_audit_logs_app_id', table_name='api_app_audit_logs')
        op.drop_table('api_app_audit_logs')

    if _table_exists('api_app_tokens'):
        op.drop_index('ix_api_app_tokens_jti', table_name='api_app_tokens')
        op.drop_index('ix_api_app_tokens_app_id', table_name='api_app_tokens')
        op.drop_table('api_app_tokens')

    if _table_exists('oauth_apps'):
        op.drop_index('ix_oauth_apps_owner_id', table_name='oauth_apps')
        op.drop_index('ix_oauth_apps_client_id', table_name='oauth_apps')
        op.drop_table('oauth_apps')

    # ### end Alembic commands ###
