[unix_http_server]
file=/var/run/supervisor.sock
chmod=0700

[supervisord]
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid
childlogdir=/var/log/supervisor
loglevel=info
nodaemon=false
minfds=1024
minprocs=200

[rpcinterface:supervisor]
supervisor#rpcinterface:1.0

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/nginx.err.log
stdout_logfile=/var/log/supervisor/nginx.out.log
user=root
depends_on=
priority=10

[program:gunicorn]
command=/root/.local/bin/gunicorn -c gunicorn.conf.py run:app
directory=/app
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/gunicorn.err.log
stdout_logfile=/var/log/supervisor/gunicorn.out.log
user=root
environment=FLASK_ENV="production",DATABASE_URL="sqlite:///smarttable.db"
priority=20
depends_on=
